title: Cats as a Service
description: Cats!
name: Christian Koys, Chromosphere IT
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot
show_downloads: ["true"]
