title: Blog
email: ckoys@tutanota.com
description: my private blog
permalink: /:year:month:day/:title
url: https://ckoys.github.io
baseurl: /
twitter_username: JarisDax
github_username: ckoys

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-spaceship

# variables
name: Blog
google_verification: null

# File management
include: [".htaccess"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
