title: Cats as a Service
description: Cats!
name: Christian Koys, Chromosphere IT
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
